services:
  - docker

env:
  global:
  - secure: "Aw9GHVg08eJ58N7EVxwiihvDklyFk+zpTzPHh4sxgi3v3Mc37AXKZF4QnRJ4lZT178tCIqmAl85t1b5vWSJ/5PQn2lhoOHqFoMuwmCcT3ODb6AWFM41joARxPTEVqrerF+K6rjFqE4XQXWQlLvuECTpDUmnf6yRFCy2UNIiFIt9J5XMctCHvhcFW/duzwAEh1VyPLTxD9WOa63YpDLJVsrr48j6EeoPWZsojgcaH8p5nW9M6SEQ22j2SvPzrF1rSMRUGBozPPlHy5HF7Jxw/UOYcdPVS5iIVqp33GJibedHzK/27fB1DHxQjvxNWSa91rc+/Xj9GBM1ZMIwaf7VYWzqE/wKoGwVU1uoAVjHfHC7poT4U23Wr6iOFIKNeb70OTE2+p8+xfZ0LFOCK6VqrgMSqOi9Ic4SVN4BX8ZCqqcrI5NvL/KF+TH3knW6z3ba6gv1v6PqBkwOM6G77ek9RDib73GmCHolmnZB7ZjayfnBRo+FsG+egCh6tgzlwN/QLmMrRE9C/MhXAKdibF7IC28SctnZGW0k8BlysVPZhZ7RBGT7KjgDZgZHw9y4T0gVrTFAGFYJxf5FO4c0MYPcZxb+VWgVEfex1Yz+9PCDTN6OUNUP+y5zxzbXnkoJfTb0NcFNDJAy5lX6H+7ZaGtG7kZGAQnoBIudPtf8ia6CWNWk="
  - secure: "aGH+VHfgUkkF991stTKHc0M/gr+INrTAiKfNHEXeZzeWJ2z5ULKMOXxApxo+YShVXmzR4NEkOwenRdnHh0Ec8Lwrt7CNwtg3WXrBzRVR4XGz6rrYw1WQDgWImi0kvEPHoxc3KjMGSbgTyyMsZBn/1R/nFq/3m/cf1sYMXF9QDfRJgji8SVQTLVoIOYBPy5vI1KpeHrJNPjfH4/OShiFY3ZDky31uu+31YvUywRuF8eEaX5/f1t/IfPlBPhf5zZUfPxZgY/HR6o6ualVXCGtKaMBizTZjTudvAqt4ruSHJ8eiQRjdcOwkOGT6CUEv01xa2nSXFisrmMXxnINmW7rPzb7Ovxe1e8UGK4NnoYhNEimXRI2yC/tyy40vviHGfEVkaEcuizOLIYWyAENgV7xPBJVa9CKiQwI1J8RJVedjlgJVFIaFe6SRI/EqJ5fDeQ/cBmSn3XvMADojX2QT+S4ZPZNTON8JWHQtejXfUR9GtAAjkzaPF7USNFQ2zkF1E3b7g830eUMqrfW1OgeTd5VCpawqystLVTWi881BB5NrnkEnM9eac8mP47w8yLinkE9txqf1V1HTESSX7m3TlKaKjWkxyboGvoACgh9Nos7QRLZqM4FkqET34wMibPrTWjevJb5ybHVgFyHmngHZdZRyliUP3xAm/eRNCzpzmqHo3vw="
  - secure: "M4aULg3Vbu6kQbjMc4GXH6h4Ji3mYFPqdrzG1amAIpiktY0LFhqC3hTL8QWNXeIh0rCsOmNIf50VpBQ8S+v2078twfFDCNZnU1wkfQ7ENGiyZU8vLhynXLPWSpgxVYr2T9y82c/KiyNad6JQo+ZBYxtCLUSO9k6hFsN837gv5ejNjP7h9C2rPC4rfhkAihun1kALDW+8y9/NGTqrCHtkhDIByCnpNVYkyNkTmKJYOZ2Oe7A/8+yStSUz0vcu+BObXRTk/lB8WdnB/RbYFcCDDrM/NPuHcse5knwVh4tBII0Ahw5tx1vfUT2ayBdBgxRkuLeqvY83G3lFyCCPoPNitkp6fFm4SlxHyIe0MHDf1gwPbNi95vKYBjy56l6K1Zi+TMXrBSKbq8f3JyrYME4s6TgY2EQI/eVu+npiOp1414s5mXPMaWu/niajCy4CViYM8IT8BUjSIbZYYIUSYWRHrlsGljE3cX7nKHqZ4ldiYPc/zr5Jh7Lkr7/ic4joSPRKupmcYYlhfuLRSBA2kunBnKqHyLVc5GFLrv4Eh1rcz8l+UXosY46no9+qvsUpLdQFid9dAPd2HIy4KHAzxD58nLtpIwqTCMx1jdP5ecZwbjmCN2W0tmQ4LIszHgU+sIQ18CXP470mLWKJgPnE/ngQ93yMYLpHm39iraFhQjAcC10="
  - FLASK_APP="app"
  - FLASK_ENV="development"
  - MONGO_CLUSTER_NAME="cluster0.vwqib.mongodb.net"
  - MONGO_DB_NAME="ppp-board-test"
  - LOGIN_DISABLED=True
  - DOCKER_USERNAME=perryjones
  - DOCKER_REPO=ppp

script:
- docker build --target test --tag my-test-image .
- docker run my-test-image tests
- docker run 
  -e FLASK_APP
  -e FLASK_ENV
  -e SECRET_KEY
  -e MONGO_CONNECTION_STRING
  -e MONGO_DB_NAME
  -e LOGIN_DISABLED
  my-test-image tests_e2e

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis_docker.sh
  on:
    branch: master
    condition: ${TRAVIS_PULL_REQUEST} == "false"
