services:
  - docker

env:
  global:
  - secure: "Ruhc3gnB4Mivx4D3jFVdnAZNdUn7F1dQFmq3Qoyg2VZafaiqjCe4FvjeYf+R9C9PDzd+8jAfeIsYvfFdGTCveQnUmz0/xWwnGsbS7MUKLsIyswOLapbGQXuGSEoiVbeZeLok+V1BUwCBLctxPDBeVxeSvGUcxc/Gd2Up6OCYF4dbgunGfHYb3W8jqRq7xBD2dpzSZju++AU9aPVEGmIKWjYmnTH5t5nF5GY2iuOh85W90AUiZm0UeNMKa/dfq+Wa5KSGTQYbHaHflp4itb9FMxPMWSPp+YFKJ+fWSGOmFjE7m6y+kzJGtuZe2cFDXqC2OaMh/UY8wAE2tiZDnsoZDAaRE6ZOE3RYDzPUY0epBg6+q4Ks1l8OsmG1fu4JFH2nS18LRlWJuEuGZ8xbesMMvTIpH8R2pWPbnkiBsmjYwYeC92/5bVwyX0MNk8D4QVwNMa9KHzl6YRAc1MLXkd/niSSvXWPRa4dJ4KXoU4utzydL7Qf4hoJeaEN2h32gploUBK6xvNZ12XC6h7zf7hZ0a4tXTMYYoHJpQ3jRfVJrvgjNHOww5UHPlSLc4A28hYl6T1pXxWnSK8BV94FTT1BHOitxwOOID+fSIHFCn1lMecsDs/Q2Jm4wsxSJh1jXhgoGJjk11HtIzkgihM+4Z7/+uGmj2VE62Ieb96YQ5xcwBQw="
  - secure: "c8XHGa5jqogA0RRS6wbafCwXIkizIe3GwpbA5I0px0qRiH3ZSEzTxDtmVDunZaM0iUKxawX9jp3bZjnmHf4lDGyTMwacWDhW8ZLCmoIkkYeuoW8ltzzej8pA/Mqh5yECK+wgyHPsfFBvLYo8TP2N3QQO4GSuyo5SOXAaTjqlfg92CX1qsqKNrcQbVJwB0vNkgaQRAYaxwjjcnQEH4bzyQrnleaqyGmULLnb5VY0jcGE35oJ2s2yxaFehmUmGYpcbo+9UA+GMK/ePEew+lXrpPaM9I3bXh/XtFJusQVujt/4R88RLRmMcL8TdfwrhMCFOHx7uT1DM5GbKgYkweCKIHnn+EL4cYIM944+W3pk6iR6JtVkOxvSBkNF2be2wKt083Jwt2RdRnM75qkkGJzIsYUz3+ObWelzGm3SfKmaUY7yD+5XPwzXTsJFto4waXXwKRUa1wqmBcnvawdnd+t0f9WeJQnvnuMxSucMfKl3u6c2eyidFErT+Ddvks/CjRSB0RtGtTzTiR2MSpg5OU+V/JP8mmsJcQedy3ove6Z6WE3rPwwtn6/HcOqE2eC4/cbBMaJt+l/ZNaDXJyWPM3JyUWF8ICBHPWCb6y+9xW0LM+qenBfd9xX+/9nPBJDRGdrS7k796cidk8wAUtdN/oxMRrn3TiwieTtul5toHd4hDF8c="
  - secure: "lxQBb/9XRIvsmwlnrAEqBQqx0CcPrCxMkthoY256DQ/8qceIZZfJukb+ppfh7EQ2/Ho8nOUttcmDj3eRfOjQGp3t/6kEn2d1AfmOYZ2OB3E7y41FHAl7NYfCbgibdWrT2Sqw5zfgORj21SKFbpNVBza55jFgIGVD37J9rW75YkOx2rAZdAKb7tE4HLN/4lAIzP102KwkXxweUMy89+obgDh5pEJ3pvchAU5BmUJUJkXQ/1i9S9AKKYQRnTWHmSLY3enKmFJCoNkuuL6XsnLMJUQ9hlmFPaVCULeN2+3u7299Ne/wxk7+JrAcoFY1q/DaVl8FKbg70TDkzuKoFyv1ebsvGApEj8fKqOeYxHv7AqxukITVh0YzyfUgMcVNE+WsWFPnxeNXXo5UviBgtqzeCVkDlkd7DGIkso6GsNTWmgyiYs3GKAEtJLqiPheNii1+2kfMXnl6wEjrLKV+okti54HBCd5eE+NpAu7+wL/nay0dEubgUPp9Yoy/LX1ZqLGA4K0ZzXIcEF5ZXq8jI5hPGk3mTNi8ntoFwVE/KRSzJKHoxJr6G/xtmckcRGnYoO1vT9G5RObhMUuA3EW+iv8o0fS3WmJfYpLdjna/+Cdv9EqGR0Mv344DZjlr7r6WvFbQzjUCuqeaC577FegA6TeTYTR9rjo3S6juo9pd8SYw6MA="
  - secure: "cYOBXTce/J6tky0dUMzlViN0xpEMatXR7+/GizUH/muZzx86lKPPrKeiMqOqKj+Au4vqqSt0GhKf56krgNVGb2yB/maXk0cwJzpCN7MnqHrwV/SXSxjdsLozLcGxVOJI2Cc59ETaFKgEE0pgQCLLigIHwwV6OfE1/WLzFFKBlKkVDILh6OZw9p6aW0jSlSiIJv0lHxOrAil7m9B17PGB8DpLhVNaHyVrqyJ1nVwk4jCVy6A11Yr6Q0/VLEVuwZb/PaCBn6AJooV0j9msAhQuxRa0ypvXgezw1OOSGejMW1VF8433/UVTIFrHUlV3Z3axnCGZLBJWJGTOXqVqX7omGhixTrTKrJT0H5NUWjfxkowlCflGjXlzxWLNt7K+nqVyTWljlbvZbwhAllZ+sDMPkD21KWgEeO9nx5biKZhHfToPRL7Ld//p5LGP5+smui6/tuGJpCT5uOmsM+ZkMLu77fGF107RbPxl5XrFuREo/Ix0VCvc04ki/1auwF2tO4IFEJt/jK27WIcHE5br7FnwDZUjvFE0vIqvIS7o7wLzNg2rHO5p2UGAGbThJt0MFzT5ToxuqHh96mK2TaYUsBp0m/MtAoNb8gQhU6sjTKbemfKtNA0PJ7mf8ukue+fXz3iF35sSzNSNKzvm1WiZ53p12EgYAoszX0Xtyz3YESWQBLY="
  - secure: "tSBhcO4FNL5KpvxIDIahKWM3DdWNamuJD7drCkssoLU9F5pTC+hcuGK+OzEUClxo6UbVLtynPppyYWPkBTv8tih0PACxm7mb+D7/Vp2AbET6VA0FY9PbGyz7EDa6VfNchW9mLrsaIBnj6WrFumg3K8aCXLVcpAhrxdXe/8QqMZMurfIEeTKRfqB/PBi6Mbagq5CaDh7ncNMw1sBYmrHcDkHcKod7ws/ngym8JMbY1O0hMeJFpec6i4+gzb2mJRGWv77UGHi+UK1NgK4wDn2bpCiCL1E3jdHkqZtyqPrGop/nhXTmgPgFqauLYqNYz9Bi+K03/hCcE7RBU1vV5V+fZn9rr00nfNyzGMXr0+fz8+bdmBClHgdiS/Q+QGeA0SJDV1pZ/5T9NxGwk+eAcFmqIMEHdngtSfNfnUw2rk0AK/AM5lP0K22KCQLVbkMOBvwTib2U22uC+wW2ljVN3ym69sE+loJQNcTroVtbqQRy+dxprIAxAKhNGE245izbRD077g3OR4TuqBLs0IdfFh2OJJNmh8PBoxFxZRJXDunlOKuV4DHVPbI/e/iIJVYB9zgY75ixOF535NUCodGzrncFCRJuUksj6OSsjKOC+jvC+WbSqZWephrijMItVJuM06IRocu2jL8762w7rTaBcpJdczflTW8Y1kgxgImrljX5Xkg="
  - FLASK_APP="app"
  - FLASK_ENV="development"
  - MONGO_CLUSTER_NAME="cluster0"
  - MONGO_DB_NAME="ppp-board-test"
  - DOCKER_USERNAME=perryjones
  - DOCKER_REPO=ppp
  - HEROKU_APP_NAME="perfectproductivityplatform"

script:
- docker build --target test --tag my-test-image .
- docker run my-test-image tests
- docker run 
  -e FLASK_APP
  -e FLASK_ENV
  -e MONGO_USERNAME
  -e MONGO_PASSWORD
  -e MONGO_CLUSTER_NAME
  -e MONGO_DB_NAME
  my-test-image tests_e2e

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis_docker.sh
  on:
    branch: master
    condition: ${TRAVIS_PULL_REQUEST} == "false"
