services:
  - docker

env:
  global:
  - secure: "CgXLQEEO5g9HAzXEu91u9cqBj0PslN/8QQJ0s26SS5smkJvlQuXU70fCXHqDU8i5f9Py8NfCzJnAop1En1RvMo+W5q7lC2xQuTv0Dp54Pk8Hu59nQ+TsF61ihgQHk+TN/IqsIM7v9zGLqo27tfQCn2LFW58VsoHDtnBSBmWvCSMaoDAeQh6wIMFg3nxietMp074P9vwN0dq0S3utx6+X9BMCxGFXAdDeL8ioy6Q1PmGv55yoBLOdTlQqE5c7atizhXWU0a1UryEfOTqNvrQFkOSOv+6oaPO/hDR5rhFjZM/siWmGOZELT0vrclgwzyl++i+sv/Cyhq/eBlX4r1w87nsV1L3ukNSz2xBLTz4G29WwJkWIeVaIdcWpXNUMF51Gmi1xNDMafZmE0hB3Wkce9tPeYTLEU2WODK+UWcQSsypRWmevjqrLIbHmSKIBCZFWqvzx2O/WOMuYyRQIxsbsi/e6A12uTXlRnJPABfLjgTwmsSt8sIsPN8ElnXKuW1FKfW/MHPJmvf2QR6bpUedr1gYWfxEI4QA7yQXbrgGNBemHGjxzoMxaKfyQkwHsYykSmZINf6ITKU06cPKWBuZAIVIE+SqmoO38oHKchE/hV5apt4I58esEK0FiC7XJpni5X7xjTkmmnW8jlBj3JjHC56DZ38360ZSaCBiM9tEZ8ZY="
  - secure: "C5jycXxg+4E9AFeDQOO3MRi76uDf/zpdL7fEGbOMTEeOqYj/bC7Z0wIWUQvq2nqhnDsp8SCEamQennnmssxqWFRysEVhohIsIkmepZq4lxLXUhJ/iQfmNTDyf8xuikATIUtcJm+tOaU3+SUAP/Z1ZHJKoSawuEzhXz/epz33BsrGzYqLWL/I9y2/p9BwLmtLBSA2u2hJseqIxnj/el2/3A8ATK5XQPi7vggeS8J7mpalypoPPyMvuCa7JDTfQA3U7LnCw0tBT1NF9K3oeLlSaZbAUA3eRnBC5OApSEe/8Rgs9BqTbW/ULHJy7yNke+7r42DzD9LGy1YEvdpohdLUrY3ENX41mmTEV3uZhYY9bxldHoF4tHIQrZFrqZPktxXJJ4O/gdOG5TI6+2YX652Yb7aEpsM51AAlcbNHjF/2AsL912VWrATz5kE83mp0sGVjYivyz4XwQkBNkWNVB0tMEaz8/xOoUgPqwa1/7e8sKOrgo+HU60gBaQyYcQqPiFCHbHuJDsGNClxNVbHLemkPZPUzayZ2C8SDO4V4rUveskqT6I/v8SXp+yqQsbvr8Al+iEqe9UJwga31AorHvpM4kN0ZPiMAop4T6AcoxrHDI2zQ7KZMTJ17gh5IQXuTSlofqzfgZ6BxJ6YrltEM1Tb7rbwo1xC8Z26vW5LUjKrSdNU="
  - secure: "kFIhw7EWWhfjSzrtDgrbwEsYeftRk+nbCVU8RNCfmlEuuXc9E3TaqN01Ev5T7PoUR7yyqqMQgxYsfcxR4SfJfkJzpVEcMOTXHmxAqJtd13OuiV7sNlURatrM0RmggMbif4/lPamYaYzy+ZIdFw3uArbFAGM5spg16IVEEeTTbfkJ9CqwbatAPCdFGQIs3CoXINdmtP6w7nRD5m+fFQ7D65lTn0p8/x1pWIuFT6rLNRuKdnYrtsXeyQlSjmYM5t2G797I0zpQ0nMWJypeK5CBYAA0iipCkXly095K9EZ6GyYlwpdmSRNKhilmfP3j7VK6rf4I1xIuw1r34SsvTtperQsoPeiFFugZpIaDKogYpWudrLJ90Cm7Z/DOARoz6jNaT84SKcV6Pk4cRqIf1VUqadadZkB3+nWWdACnZmAMJEh8tW7S41mRFX0xHw+jb8Ew1fG0dI+A6ZP3ICweXJsklNRQsrYfsqW7teaREQmjEpCB4uIDNnOqqfnJB4XHcWpco1i2PShfKT9pjN6WWK4OoWv+RcSMcvFeNiccEticjRPGNZLISavYO95A4szPQ7fcheTgXrZpKCU/KkwaGxsIa6d5CmcG/IIDika5aVDEqNbOoG4yPcYTf6TGzdiJhlw3XVZBvZ0Rut78YWFUfEVxDTyV9OgnhPPBW9pRldlpzvk="
  - secure: "lxQBb/9XRIvsmwlnrAEqBQqx0CcPrCxMkthoY256DQ/8qceIZZfJukb+ppfh7EQ2/Ho8nOUttcmDj3eRfOjQGp3t/6kEn2d1AfmOYZ2OB3E7y41FHAl7NYfCbgibdWrT2Sqw5zfgORj21SKFbpNVBza55jFgIGVD37J9rW75YkOx2rAZdAKb7tE4HLN/4lAIzP102KwkXxweUMy89+obgDh5pEJ3pvchAU5BmUJUJkXQ/1i9S9AKKYQRnTWHmSLY3enKmFJCoNkuuL6XsnLMJUQ9hlmFPaVCULeN2+3u7299Ne/wxk7+JrAcoFY1q/DaVl8FKbg70TDkzuKoFyv1ebsvGApEj8fKqOeYxHv7AqxukITVh0YzyfUgMcVNE+WsWFPnxeNXXo5UviBgtqzeCVkDlkd7DGIkso6GsNTWmgyiYs3GKAEtJLqiPheNii1+2kfMXnl6wEjrLKV+okti54HBCd5eE+NpAu7+wL/nay0dEubgUPp9Yoy/LX1ZqLGA4K0ZzXIcEF5ZXq8jI5hPGk3mTNi8ntoFwVE/KRSzJKHoxJr6G/xtmckcRGnYoO1vT9G5RObhMUuA3EW+iv8o0fS3WmJfYpLdjna/+Cdv9EqGR0Mv344DZjlr7r6WvFbQzjUCuqeaC577FegA6TeTYTR9rjo3S6juo9pd8SYw6MA="
  - FLASK_APP="app"
  - FLASK_ENV="development"
  - TRELLO_BASE_URL="https://api.trello.com/1"
  - DOCKER_USERNAME=perryjones
  - DOCKER_REPO=ppp

script:
- docker build --target test --tag my-test-image .
- docker run my-test-image tests
- docker run 
  -e FLASK_APP
  -e FLASK_ENV
  -e TRELLO_API_KEY
  -e TRELLO_API_TOKEN
  -e TRELLO_BASE_URL
  -e TRELLO_BOARD_ID
  my-test-image tests_e2e

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis_docker.sh
  on:
    branch: exercise-8
    condition: ${TRAVIS_PULL_REQUEST} == "false"
